version: '2'
services:
  hubble-nginx:
    build: ./docker/nginx/.
    container_name: hubble-nginx
    depends_on:
      - hubble-php
    ports:
      - 8101:80
    volumes:
      - ./:/var/www/html

  hubble-php:
    build: ./docker/php-clear/.
    container_name: hubble-php
    volumes:
      - ./:/var/www/html

  hubble-mysql:
    image: mysql:8.0.16
    container_name: hubble-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=hubble
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

  hubble-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: hubble-elastic
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=hubble-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./storage/.elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300